kind = "mobile"
previewPath = "/mobile/"
title = "Fiqh Darah Mobile"
version = "1.0.0"
id = "artifacts/fiqh-darah-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 20645

[services.development]
run = "pnpm --filter @workspace/fiqh-darah-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/fiqh-darah-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/fiqh-darah-mobile", "run", "serve" ]

[services.env]
PORT = "20645"
BASE_PATH = "/mobile/"
